// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcq7L3NBa9BPw0DNy96ljbWQBJy0EnWEY',
    appId: '1:661237482006:web:ec2bf58622ee67ad6fab37',
    messagingSenderId: '661237482006',
    projectId: 'hosan-notice',
    authDomain: 'hosan-notice.firebaseapp.com',
    storageBucket: 'hosan-notice.appspot.com',
    measurementId: 'G-4RE0QQPXW7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBapUU4VVQmJbnDGhJXKl7GhBlFdrMCje8',
    appId: '1:661237482006:android:e64d5bf3b73afa346fab37',
    messagingSenderId: '661237482006',
    projectId: 'hosan-notice',
    storageBucket: 'hosan-notice.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH045WBAWsrScbxsa3TR2BLVhOQL9eeEk',
    appId: '1:661237482006:ios:919345945ec7cc146fab37',
    messagingSenderId: '661237482006',
    projectId: 'hosan-notice',
    storageBucket: 'hosan-notice.appspot.com',
    androidClientId: '661237482006-0rjbp56r74n9l7nb8h8gqdvejrl3t30l.apps.googleusercontent.com',
    iosClientId: '661237482006-8c526sr4aeadla0rn5r6pprm9p123pqh.apps.googleusercontent.com',
    iosBundleId: 'com.hosandevlab.notice',
  );
}
